---
- name: Copy /etc/ssh/sshd_config to bckp directory
  copy:
    src: /etc/ssh/sshd_config
    dest: '/root/backp_{{ date }}/login.defs'
    owner: root
    group: root
    mode: '0600'

- name: Copy jinja template to /etc/ssh/sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    group: root
    owner: root
    mode: '0600'
  notify:
  - Restart sshd
